# Generated by Django 5.2.4 on 2025-07-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_egresados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosBecario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(verbose_name='Cédula:')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres:')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos:')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico: ')),
                ('telefono', models.IntegerField(verbose_name='Teléfono Celular')),
                ('telefono2', models.IntegerField(verbose_name='Teléfono Local o Alternativo')),
                ('fecha_naci', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('lugar_naci', models.CharField(max_length=200, verbose_name='Lugar de Nacimiento:')),
                ('nacionalidad', models.CharField(max_length=200, verbose_name='Nacionalidad:')),
                ('titularidad', models.CharField(choices=[('pregrado', 'Pregado'), ('postgrado', 'Postgrado'), ('maestria', ',Maestria'), ('doctorado', 'Doctorado')], max_length=200, verbose_name='Titularidad:')),
                ('idiomas', models.CharField(max_length=200, verbose_name='Idiomas qué Domina:')),
                ('ocupacion', models.CharField(max_length=200, verbose_name='Ocupación Actual:')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección en Venezuela:')),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario_egresados.estado')),
                ('municipio', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario_egresados.municipio')),
                ('parroquia', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario_egresados.parroquia')),
            ],
        ),
        migrations.CreateModel(
            name='DatosUniversidadBecario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_beca', models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional')], max_length=200, verbose_name='Tipo de Beca:')),
                ('carrera', models.CharField(max_length=200, verbose_name='Carrera Cursada:')),
                ('fecha_ing', models.DateField(verbose_name='Fecha de Ingreso')),
                ('fecha_egr', models.DateField(verbose_name='Fecha de Egreso/Graduación')),
                ('tipo_becario', models.CharField(choices=[('extran_venz', 'Extranjero en Venezuela'), ('venz_venz', 'Venezolano(a) en Venezuela'), ('venz_extran', 'Venezolano(a) en el Extranjero')], max_length=200, verbose_name='Tipo de Becario:')),
                ('universidad', models.CharField(max_length=200, verbose_name='Nombre de la Universidad:')),
                ('becario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario_egresados.datosbecario')),
            ],
        ),
    ]
