# Generated by Django 5.2.4 on 2025-07-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_egresados', '0002_datosbecario_datosuniversidadbecario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatosUniversidadBecario',
            new_name='DatosAcademicos',
        ),
        migrations.RenameModel(
            old_name='DatosBecario',
            new_name='DatosPersonales',
        ),
    ]
