# Generated by Django 5.2.4 on 2025-07-31 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_egresados', '0003_rename_datosuniversidadbecario_datosacademicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosacademicos',
            name='becario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_academicos', to='formulario_egresados.datospersonales'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='cedula',
            field=models.CharField(unique=True, verbose_name='Cédula:'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Correo Electrónico: '),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono Celular'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefono2',
            field=models.CharField(max_length=20, verbose_name='Teléfono Local o Alternativo'),
        ),
    ]
