# Generated by Django 5.2.4 on 2025-08-01 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario_egresados', '0004_alter_datosacademicos_becario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='cedula',
            field=models.IntegerField(unique=True, verbose_name='Cédula:'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(choices=[('v', 'V'), ('e', 'E')], max_length=200, verbose_name='Nacionalidad:'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefono',
            field=models.IntegerField(verbose_name='Teléfono Celular'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefono2',
            field=models.IntegerField(verbose_name='Teléfono Local o Alternativo'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='formulario_egresados.estado'),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parroquias', to='formulario_egresados.municipio'),
        ),
    ]
